### ISSUE TITLE
tailwindcss update broke font class

### ISSUE THREAD

**Issue by marijnvdwerf** [oszuidwest/teksttv#43]
Since upgrading to TailwindCSS 4-beta, the font rendering broke. In previous alphas, the class `font-tahoma` would set Tahoma as the font. But since switching to the beta, that doesn't work anymore.

**Comment by rmens** [comment]
Fixed in https://github.com/oszuidwest/teksttv/commit/b41496f98175301b66b9fbc26af526f098436eba
